UPDATE wp_38_posts SET post_excerpt = 'William E. Lamie, Co-Founder and CEO of Express Logic Inc., is the architect of the ThreadX RTOS. Prior to founding Express Logic, Lamie authored the Nucleus RTOS and co-founded Accelerated Technology. Twenty-five of Lamie\'s 30 years\' experience in developing embedded systems has focused on the development of real-time operating systems. As the architect of three RTOSs that have enjoyed widespread commercial adoption, Lamie can be credited as the source behind more than five billion RTOS-driven devices.' WHERE ID = 2674;
UPDATE wp_38_posts SET post_excerpt = 'Lou is Communications Technology Editor for Electronic Design. He covers topics such as wired and wireless networking. He is also editor for Mobile Dev &amp; Design.' WHERE ID = 2675;
UPDATE wp_38_posts SET post_excerpt = 'John J. Simmins&nbsp;is a technical executive at the EPRI, where he manages the information and communications technologies for distribution projects.
His current responsibilities focus on bringing thought leadership in the area of integrating diverse applications such as AMI, MDMS, DMS, CIS, GIS and OMS.
Simmins also leads the EPRI efforts in the use of augmented reality, social media, data analytics and visualization to improve outage-restoration efforts and grid resilience.' WHERE ID = 2676;
UPDATE wp_38_posts SET post_excerpt = 'Karen Field is Executive Director, Content for Penton\'s new Internet of Things Initiative and IoT Emerge event. She has 25+ years experience developing content for an audience of technical and business professionals and a reputation for challenging conventional thinking and taking a novel approach in the creation of world class editorial and conference programming.Most recently she launched the Internet of Things Summit at the Embedded Systems Conference and has covered the emerging issues associated with the Internet of Things extensively for EE Times, EDN, and Embedded.com.Karen has a mechanical engineering degree and a master\'s of business degree from the University of Minnesota and Boston University.' WHERE ID = 2678;
UPDATE wp_38_posts SET post_excerpt = 'Dwight Bues is a Georgia Tech Computer Engineer with 30+ years of experience in computer hardware, software, and systems and interface design. He has worked in Power Generation, Communications, RF, Command/Control, and Test Systems. Dwight is a Certified Scrum Master and teaches courses in Architecture, Requirements, and IVV&amp;T.' WHERE ID = 2679;
UPDATE wp_38_posts SET post_excerpt = 'Mark is an expert in maintenance management, having racked up an impressive track record during his time working in the field. He also has extensive knowledge of, and practical expertise with, the National Electrical Code (NEC). Through his consulting business, he provides articles and training materials on electrical topics, specializing in making difficult subjects easy to understand and focusing on the practical aspects of electrical work.Prior to starting his own business, Mark served as the Technical Editor on EC&amp;M for six years, worked three years in nuclear maintenance, six years as a contract project engineer/project manager, three years as a systems engineer, and three years in plant maintenance management.Mark earned an AAS degree from Rock Valley College, a BSEET from Columbia Pacific University, and an MBA from Lake Erie College. He\'s also completed several related certifications over the years and even was formerly licensed as a Master Electrician. He is a Senior Member of the IEEE and past Chairman of the Kansas City Chapters of both the IEEE and the IEEE Computer Society. Mark also served as the program director for, a board member of, and webmaster of, the Midwest Chapter of the 7x24 Exchange. He has also held memberships with the following organizations: NETA, NFPA, International Association of Webmasters, and Institute of Certified Professional Managers.' WHERE ID = 2683;
UPDATE wp_38_posts SET post_excerpt = 'Martin Rosenberg is Director of Content, Energy for Penton Media.He was editor-in-chief of EnergyBiz, a national publication covering the energy industry, from its launch under his direction in 2004 through 2014. The magazine was recognized as the best publication covering the \'energy/utilities/engineering\' sectors in 2005-2008, 2010 and 2012.He has written extensively about energy, technology, finance and international business. His freelance work has appeared in the New York Times, Seattle Times, Japan Times and other publications. He and previously was editor-in-chief of Utility Business, a monthly publication that won numerous journalism awards.He was a business writer at the Kansas City Star from 1985-1998 and worked for newspapers in Oregon. He was a Fulbright Fellow to Japan, where he studied economics, and received a grant from the German Marshall Fund of the United States to study international agricultural issues.He is a graduate of Reed College and holds a master\'s degree from Northwestern University\'s Medill School of Journalism. He and his wife, Matilda, reside in Kansas City and have three children.' WHERE ID = 2684;
UPDATE wp_38_posts SET post_excerpt = 'Mike Romeri is a managing partner at OPS Rules, a leading analytics and optimization firm focused on helping companies identify and capture hidden opportunities in their manufacturing operations and supply chains.' WHERE ID = 2685;
UPDATE wp_38_posts SET post_excerpt = 'I am a nice guy that is doing the best he can. _ I do business under different company names. _ They all share my Dun &amp; Bradstreet (SM) D-U-N-S (R) number 159989362.' WHERE ID = 2736;
UPDATE wp_38_posts SET post_excerpt = 'Leah Scully is a graduate of The College of New Jersey. She has a BS degree in Biomedical Engineering with a mechanical specialization. &nbsp;Leah is responsible for Machine Design&rsquo;s news items&nbsp;that cover industry trends, research, and applied science and engineering, along with&nbsp;bi-weekly product galleries.' WHERE ID = 2737;
UPDATE wp_38_posts SET post_excerpt = 'Tom Kaneshige is editor of Five2ndWindow, Penton&rsquo;s independent news site helping marketers and line-of-business executives get ahead of the mobile disruption happening to the customer experience. You can reach him at tom.kaneshige@penton.com.' WHERE ID = 2772;
UPDATE wp_38_posts SET post_excerpt = 'Associate editor Travis Hessman examines trends in manufacturing technology, covering developments in automation, robotics, digital tools and emerging technologies. He also reports on the best practices of the most successful high tech companies, including computer, electronics and industrial machinery / equipment manufacturers.  Travis returned to IndustryWeek in 2012 after working as an intern for the publication back in 2001 and later as a contributing writer.  Travis received his bachelor&rsquo;s degree in English from Kent State University and his master&rsquo;s in creative writing from the Northeast Ohio MFA consortium via Kent State.' WHERE ID = 2816;
UPDATE wp_38_posts SET post_excerpt = 'See my profile and let\'s get connected at LinkedIn' WHERE ID = 2841;
UPDATE wp_38_posts SET post_excerpt = 'Megan Ray Nichols studied the future of aerospace composite materials in her most recent contribution to AmericanMachinist.com. She is an amateur astronomer and environmentalist and writes on a variety of scientific topics. Follow her on Twitter @nicholsrmegan.' WHERE ID = 2845;
UPDATE wp_38_posts SET post_excerpt = 'IndustryWeek&nbsp;focuses on manufacturing and industrial companies, trends, technologies, lean leadership, workforce best practices and production&nbsp;' WHERE ID = 2861;
UPDATE wp_38_posts SET post_excerpt = '\"Take nothing personally\"' WHERE ID = 2889;
UPDATE wp_38_posts SET post_excerpt = 'Alan writes about the auto industry in Australia and&nbsp;New Zealand, as well as other Asia/Pacific and emerging markets for&nbsp;WardsAuto.&nbsp;' WHERE ID = 2898;
UPDATE wp_38_posts SET post_excerpt = 'Robert Vamosi, Security Strategist for the Software Integrity Group at Synopsys, is a CISSP and author of&nbsp;When Gadgets Betray Us: The Dark Side of our Infatuation with New Technologies. He is featured in the history-of-hacking documentary,&nbsp;Code2600. As an award-winning journalist, Vamosi has been writing about information security for more than 15 years for sites including Forbes.com, ZDNet, CNET, CBS News, PC World and Security Ledger' WHERE ID = 2910;
UPDATE wp_38_posts SET post_excerpt = 'Eminent Test-Transformation Consultant, Non-Exec, Thought Leader, Advisor.' WHERE ID = 2919;
UPDATE wp_38_posts SET post_excerpt = 'Dr. Jonathan Laserson is a senior algorithm researcher at PointGrab, and a machine learning expert and consultant. He holds a PhD from the Computer Science AI lab at Stanford University and was a lecturer at Bar-Ilan University in Israel. After academia, he worked at Google and used machine learning to enhance the security of Google user accounts. At PointGrab, his primary focus is the practical use of deep-learning algorithms in embedded environments.&nbsp;' WHERE ID = 2929;
UPDATE wp_38_posts SET post_excerpt = 'Kevin Jones, Editor, American Trucker, Jones has an odd fascination with the supply chain. As editor of American Trucker, he focuses on the critical role owner-ops and small fleets play in the economy, locally and globally. And he likes big trucks.' WHERE ID = 2949;
UPDATE wp_38_posts SET post_excerpt = 'Adrian Caceres is passionate about connected products and has made connectivity the core of his professional career. As co-founder of Ayla Networks, he&rsquo;s helping to shape the future of the Internet of Things (IoT). Adrian came from Amazon&rsquo;s Lab126, where he was the technical lead for the Kindle wireless software team and helped launch the first Kindle with Wi-Fi. He holds a B.S. in electrical engineering from Worcester Polytechnic Institute' WHERE ID = 3033;
UPDATE wp_38_posts SET post_excerpt = 'IoT systems development' WHERE ID = 3039;
UPDATE wp_38_posts SET post_excerpt = 'Nancy Crotti&nbsp;began her&nbsp;journalistic career as a teenager, and&nbsp;continued it at Syracuse University, writing for the Daily Orange.&nbsp;She landed her&nbsp;first newspaper job at a Philadelphia weekly called the Germantown Courier. She took first prize for investigative reporting among weekly newspapers in a Pennsylvania Newspaper Publishers Association contest for a story about alleged sexual harassment of teachers.
As one of eight staff writers for the&nbsp;daily Delaware State News&nbsp;in Dover, DE, she covered state, county and municipal government; crime, business, agriculture and real estate. She wrote many profiles and feature stories and wove colleagues&rsquo; coverage of Hurricane Gloria into a cohesive story.
Later, she had a staff writing position at the Asbury Park Press&nbsp;in New Jersey, where she covered municipal government, residential and commercial real estate, interior design, education and business. There, she won third prize for investigative reporting in a New Jersey Newspaper Publishers Association contest for a series on government disposal of properties seized from financial institutions.
In 1999, she&nbsp;moved with my family to St. Paul, MN, where I began my freelance career, writing about healthcare, residential and commercial real estate, business, law, medical technology, interior and landscape design, and gardening, as well as a wide variety of feature articles. Publications that have featured my work include the New York Daily News, the Minneapolis Star Tribune, the St. Paul Pioneer Press,&nbsp;the Minneapolis-St.PaulBusiness Journal, Commercial Property Executive, Qmed.com,&nbsp;Finance &amp; Commerce,Minnesota Lawyer, Politics in Minnesota, Minnesota Medicine, Saint Paul Illustrated,The Line (an online news magazine), The Mix (the newsletter of the Twin Cities cooperative grocery stores) and the alumni magazines of St. Catherine University, William Mitchell College of Law, and St. Olaf College.' WHERE ID = 3072;
UPDATE wp_38_posts SET post_excerpt = 'Founded in 1981, Bloomberg reports on&nbsp;international business&nbsp;developments and other news.' WHERE ID = 3079;
UPDATE wp_38_posts SET post_excerpt = 'Fred leads the overall strategic direction and management of the association. When he&rsquo;s not doing that he is jumping in the fray with companies each and every day to figure out their needs and provide insight, connections and collaboration. He uses that spectrum of experiences, and a dose of sarcasm, in his daily business and personal endeavors.A native Californian, now a deep-rooted
Chicagoan, he is always seeking out ways to get in the water and enjoy the outdoors through biking, hiking or kayaking with and without his wife, labrador and three children.' WHERE ID = 3099;
UPDATE wp_38_posts SET post_excerpt = 'Richard is known as a hands-on, technology entrepreneur with a track record of building and transforming early-stage technology companies such as Ensygnia, Swivel Secure, Mobix, SAVortex, Clearswift and Tumbleweed.As Chief Executive and a founder of Ensygnia, Richard conceptualised and patented a visual alternative to NFC called Onescan.Ensygnia\'s Onescan platform enables a consumer to go from looking to buying in under 10s from first contact - including new customers!At the Mobile World Congress over 1500 industry leaders voted Onescan as one of top 3 the innovations most likely to have the greatest impact on the mobile industry over the next ten years!Ensygnia beat tough competition from AirWatch, CloudX, Metrical and SpatialBuzz to win the Mobile Industry Awards 2014: Best Use of Software.In his spare time, he enjoys Ceroc &amp; Scuba, is a campaigner for the rights of vulnerable adults and mental health issues when possible working with Zacchaeus 2000 Trust and Mental Health Research UK as well as mentoring Nicholas Fearn a young man with Asperger\'s. Also enjoys mucking around with molten glass, composing music, painting and digital art.' WHERE ID = 3151;
UPDATE wp_38_posts SET post_excerpt = 'Alberto Lopez is an independent consultant that knows how Food and Beverage business works; he is aware of innovations in OT Operation Technology and Information Technology and with relevant IT service providers and vendors.He demonstrates leadership skills, including the ability to listen to employees, collaborate and network with other C-level managers and negotiate with the suppliers, he can run a department, oversee staff, balance KPI and budget and manage IT as part of a business function.He is comfortable with managing change -- both low-tech and high-tech change and changes in business goals; he actively monitors the competition; he can demonstrate which innovations will be worthwhile and determine how technology can further improve the business process and successfully market his ideas for change.He provides his customers a portfolio of software solutions which enable the integration of data, Operation, Physical Asset and Quality Management, helping them to get a more realistic and holistic view, about the cause of Unscheduled shutdowns, giving another perspective that goes far beyond the maintenance and engineering functions.He dedicated to the support of the improvement of production processes, operator performance, and Asset utilization, using tools such as Manufacturing 4.0. Lean Manufacturing and Total Productive Maintenance and obtaining real-time data of the entire manufacturing process as well as the critical aspects of business like operational costs, cash flow, margins of sales, quality of the product, etc.He has done works in Spain, France, Portugal, Holland, Italy, Germany, Sweden, Taiwan, Peru, Chile, Bolivia, Colombia, Ecuador, Pakistan, Saudi Arabia, Kuwait, Egypt, Philippines, Trinidad &amp; Tobago, Barbados, Suriname, Guyana, Jamaica, Nigeria.' WHERE ID = 3167;
UPDATE wp_38_posts SET post_excerpt = 'Candace Roulo, senior editor of Contractor&nbsp;and graduate of Michigan State University&rsquo;s College of Communication Arts &amp; Sciences, has 15 years of industry experience in the media and construction industries. She covers a variety of mechanical contracting topics, from sustainable construction practices and policy issues affecting contractors to continuing education for industry professionals and the best business practices that contractors can implement to run successful businesses. &nbsp; &nbsp;' WHERE ID = 3217;
UPDATE wp_38_posts SET post_excerpt = 'Chris Kocher, a 30-year veteran of Silicon Valley and multiple innovation and investment cycles, brings a wealth of strategic and hands-on operating experience to help companies build both revenue and shareholder value. He works with companies on innovating with new business models and product strategies in disruptive markets.
Chris is a founder and managing director of Grey Heron, a venture acceleration consulting firm. He has worked with investors, CEOs and executive teams to help build winners and grow long-term value. Along the way, Grey Heron has worked with more than 130 companies, built breakout category leaders, helped raise over $500 million, and supported multiple advantageous exits. Clients range from early-stage startups to Fortune 500 firms including Apple, Cisco, HP, Oracle and Visa.
Previously, Chris was a VP/GM at Symantec with complete P&amp;L responsibility for a business unit where he doubled revenues. Earlier in his career, he spent 10 years at HP in management roles at several divisions where he helped pioneer HP\'s first laser printer, its initial personal computers and early independent software vendor (ISV) ecosystem and partner programs.
Much of his work has focused on helping companies with breakthrough technologies and platforms translate them into compelling value propositions to achieve rapid adoption in evolving markets including: IoT, SAAS, cloud, big data, analytics, on-line video, digital media, ecommerce and adtech.&nbsp;
Chris earned his MBA from Columbia University in marketing and international business and his undergraduate degree at Princeton.' WHERE ID = 3226;
UPDATE wp_38_posts SET post_excerpt = 'At Crowdstory, we&rsquo;re building out a network of people interested in telling their stories and educating others on how they are bettering the world with a focus on industrial IoT deployments. Our enabling foundational work is the book Precision: Principles, Practices and Solutions for the Internet of things. In addition, our professional service offering captures stories from the field (such as real world IoT deployments) and writes, films, publishes and promotes them so ultimately the field can learn from the field. We can also analyze these stories to derive further insights into what&rsquo;s really happening in the field.' WHERE ID = 3362;
UPDATE wp_38_posts SET post_excerpt = 'Jeremy Coward is an experienced writer, marketer and community manager, specializing in articles and content creation for the internet of things and other \"connected innovation\" areas, as well as blogging on literature and politics.&nbsp;' WHERE ID = 3363;
UPDATE wp_38_posts SET post_excerpt = 'Retired corporate design executive, currently a Professor of &nbsp;Practice at Indiana University\'s School of Informatics and Computing, in the Department of Human Centered Computing.' WHERE ID = 3374;
UPDATE wp_38_posts SET post_excerpt = 'As CEO and co-founder of Portnox, Ofer is responsible for the day-to-day operations for setting the strategic direction at Portnox. Ofer has over 20 years experience in network security, from establishing the first IT security team in the Israeli Air Force to managing the security division at Xpert Integrated Systems to being Microsoft Regional Director of Security, Ofer is a proven innovator and thought leader in network security. Mr. Amitai holds a B.Sc. in Computer Science.' WHERE ID = 3377;
UPDATE wp_38_posts SET post_excerpt = 'A committed, life-long learner, I enjoy the challenges the world of public relations gives me. I enjoy variety and had the pleasure of leading many organizations and teams since graduating from The University of Alabama. I am a detailed and passionate team member, evidenced by my work in the community (Austin Chamber of Commerce) and B2B tech, cybersecurity &amp; DevOps communities (Carve Communications, IoT Institute, SHIFT Communications and Software Advice).' WHERE ID = 3391;
UPDATE wp_38_posts SET post_excerpt = 'Lynn Haber is a Senior Editor at Channel Partners. A veteran reporter, she\'s covered many IT industry transformations over the years, and admits it never gets old.' WHERE ID = 3422;
UPDATE wp_38_posts SET post_excerpt = 'Steve\'s coverage at Heavy Reading includes the Internet of Things (IoT) and related technologies, focusing on the evolution of the mobile Internet and its impact on digital life. Steve joins Heavy Reading with more than two decades of experience as a strategy, marketing and technology advisor, analyst, speaker and commentator on the mobile Internet and the emerging IoT space. He previously worked with Motorola in Germany, the U.K. and the U.S., where he led technology roadmapping, strategy, product and business development teams that developed 2G, 3G and 4G cellular devices for the global market. In addition, Steve is an entrepreneur who has founded two companies: KeySo Global LLC, an analysis and advisory firm specializing in strategy, marketing and innovation, with a focus on mobile technology; and My City Tag LLC, a digital city services platform with an initial market focus on parking. Steve holds a First Class B.A. Honors degree in Business from Kingston University, England.' WHERE ID = 3424;
UPDATE wp_38_posts SET post_excerpt = 'Zach is a regular contributor to IoT Institute, sharing his experience from engagements with major players across both industrial and consumer industry verticals. He specializes in understanding how companies are already using, or looking to use IoT technologies to transform their business.&nbsp;' WHERE ID = 3425;
UPDATE wp_38_posts SET post_excerpt = 'Tim Sherwood is VP of business development, mobility &amp; IoT solutions at Tata Communications.&nbsp;' WHERE ID = 3431;
UPDATE wp_38_posts SET post_excerpt = 'Lonnie is an Industry Principal with SAS Institute&rsquo;s energy and manufacturing business unit. He primarily focuses on helping clients understand the opportunities and risks with emerging technology and competitive market dynamics in the automotive sector. Lonnie&rsquo;s 25+ year career stems from his interests in understanding buyer behavior and attitudes while simplifying complex issues for various business roles. Having authored several market studies and white papers on customer loyalty, hybrid vehicles and other automotive trends and consumer viewpoints, Lonnie enjoys the challenge of applying analytical and technical solutions in an advisory role to his clients so they operate more competitively and financially sound. Lonnie holds a B.B.A. in Marketing from the University of Michigan-Flint and an M.A. in advertising from Michigan State University. You can find him on LinkedIn at https://www.linkedin.com/in/lonniemiller.' WHERE ID = 3458;
UPDATE wp_38_posts SET post_excerpt = 'Scott Amyx is the Chair &amp; Managing Partner at Amyx Ventures, CEO of Amyx+, Managing Partner at the Future of Fashion (with former Miami Fashion Week founders), and Singularity University/ Smart City Accelerator Mentor and Startup Board Member. Scott is a Tribeca Disruptor Foundation Fellow, a disruptive innovation awards program of Tribeca Film Festival. He is scheduled to speak at TEDx on disruption and success. Scott is a thought leader, speaker, and author on the Internet of Things and the Fourth Industrial Revolution and winner of the Cloud &amp; DevOps World Award for Most Innovative and was voted Top Global IoT Influencer &amp; Expert by Inc. Magazine, HP Enterprise, Postscapes, Top IoT Authority by the Internet of Things Institute, and Top 10 Global Speakers by Speaking.com. Scott has been nominated to the World Economic Forum as a committee member for the Future of the Internet. The Republic of Korea nominated Scott to represent cutting-edge research and case studies on the Internet of Things at the ITU Telecom World, United Nations. Sovereignties, governments, multinationals, and international consulting and research firms look to Scott for unrivaled insights and pulse on the changing emerging technology landscape.
Scott&rsquo;s feature Wiley book Strive is scheduled to come out in early 2018. Find out how doing the things most uncomfortable leads to success. Pioneering thought leader Scott Amyx shows anyone striving to succeed, regardless of who or where we are, what we do or have done for a living, or how young or old we are, that the secret to outstanding achievement is not talent but doing the things uncomfortable he calls &ldquo;strive&rdquo;. Drawing on his own powerful story of an impoverished immigrant frequently told that he would mount to nothing, Amyx, now a celebrated venture capitalist and futurist, describes his meteoric rise from obscurity to prominence, which led to the hypothesis that what really drives success is not intellect, opportunities or even network but pursuing personal change that&rsquo;s uncomfortable. In this book, Scott takes readers into his defining life moments and stories from some of the most unlikely individuals who persevered through change to become outrageously successful. He also mines fascinating insights from history and shows what can be gleaned from modern experiments in high performance. Finally, he shares what he&rsquo;s learned from interviewing dozens of high achievers&mdash;from corporate CEOs, unicorn startup entrepreneurs to global policy leaders. Strive shows how you can shape your life and your career, a life of fulfillment and joy, constantly creative and productive, one that always holds the possibility of delightful surprise.
Scott&rsquo;s second feature book The Human Race: How Humans Can Survive in the Robotic Age is scheduled to come out in 2018. Scott explores the imminent net job loss from artificial intelligence, robotics, and the Fourth Industrial Revolution and its impact on income inequality and rise in populism and nationalism that are sweeping across the globe. He explores the advantages and disadvantages of basic universal income. Scott emphasizes the need to pursue job training and labor force development in human to human services that leverage our ability to empathize with the human condition. The empathy business models and services will become the bedrock of post Fourth Industrial Revolution.
Scott has been featured on New York Times, TIME, Forbes, The Washington Post, WIRED, TechCrunch, Inc., Pew Research, Chicago Tribune, InformationWeek, Forrester, Gigaom, ReadWrite, Shots Magazine, Business News Daily, IBM Big Data &amp; Analytics, Intel, Geektime, Examiner, TechBeacon, EE Times, IEEE, El Pa&iacute;s, Costco Magazine, and television and radio programs. He has spoken or scheduled to speak at TED, European Commission, World Economic Forum, ITU Telecom World (United Nations), International CES, Internet of Things World, IoT Asia, M2M Summit, Smart IoT London, Internet of Things Security, Wearable Technologies Conference, IBM Insight, IBM Amplify, IBM Watson IoT, IBM InterConnect, Cloud Expo Europe, Cloud &amp; DevOps World, KAIST, Samsung SDS, ArabNet Dubai &amp; Riyadh, Internet Summit, Global Big Data, JCK Las Vegas, Customer Service Experience, IN3 Medical Device 360 Summit, Razorfish Tech Summit, Location &amp; Context World, Wearables TechCon, K-Global Startup, and more. Scott is the co-author of Internet of Things and Data Analytics Handbook, an academic publication by John Wiley and Sons and The Advances in Information Security, Privacy, &amp; Ethics (AISPE) Book Series: Managing Security Issues and the Hidden Dangers of Wearable Technologies, an academic publication by IGI Global.
Scott has over 19 years of large-scale strategy and implementation experience, managing double digit million dollar projects across multiple verticals. In his last corporate position as VP of Product Management, Scott helped the company be acquired by a Fortune 500 publicly traded company. Scott has also started numerous startups and successfully sold a company.
Scott has a master&rsquo;s degree in applied microeconomics/ public policy from the University of Chicago. Scott was a national Sloan Fellow at Carnegie Mellon University.
Learn more about Scott at http://amyxinternetofthings.com.' WHERE ID = 3472;
UPDATE wp_38_posts SET post_excerpt = 'Courtney Bjorlin is a freelance reporter and writer, with more than a decade of experience covering technology news. Courtney&nbsp;covers IoT-related news for IT and OT audiences for The&nbsp;Internet of Things Institute.&nbsp;She also writes for several major enterprise software companies, including interviewing customers for case studies, writing ebooks and whitepapers, and ghostwriting blogs and articles. Prior to starting her freelance writing business, she led content and executive communication at the Americas&rsquo; SAP Users&rsquo; Group and worked as a reporter at TechTarget. Courtney started her career as a daily newspaper reporter.&nbsp;' WHERE ID = 3476;
